# Generated by Django 5.0.5 on 2024-05-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstappdjango', '0002_rename_name_menu_plate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
