# Generated by Django 5.0.5 on 2024-05-28 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstappdjango', '0003_menu_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40)),
                ('menu_id_item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='menu_id', to='firstappdjango.menu')),
            ],
        ),
    ]
